# Generated by Django 6.0.3 on 2026-03-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_is_available_alter_dish_order_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dishes',
        ),
    ]
