# Generated by Django 6.0.3 on 2026-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_table_alter_dish_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
