# Generated by Django 6.0.3 on 2026-03-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category', 'subcategory', 'order', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Основная категория'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно для заказа'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, help_text='Пример: 250 г или 200/50 мл', max_length=50, null=True, verbose_name='Вес'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dish',
            table=None,
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.category', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.subcategory', verbose_name='Подкатегория'),
        ),
    ]
