# Generated by Django 6.0.3 on 2026-03-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_dish_options_alter_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
    ]
