# Generated by Django 6.0.3 on 2026-03-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_table_alter_dish_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
