# Generated by Django 6.0.3 on 2026-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступно для заказа'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order', 'name'], name='category_order_d668e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'is_available'], name='dish_categor_97dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['subcategory', 'is_available'], name='dish_subcate_4cfdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_available', 'order'], name='dish_is_avai_83098d_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'order'], name='subcategory_categor_8170cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'name'], name='subcategory_categor_02ac1b_idx'),
        ),
    ]
