# Generated by Django 6.0.3 on 2026-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_category_name_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото блюда', null=True, upload_to='dishes/', verbose_name='Фото блюда'),
        ),
    ]
