# Generated by Django 6.0.3 on 2026-03-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
        migrations.AlterModelTable(
            name='table',
            table='tables',
        ),
    ]
